export const prepareBasicInfo = (basicInfo, salesConfig) => ({
  subdominio: basicInfo.subdominio || "",
  dominio: basicInfo.dominio || "",
  linkDominio: basicInfo.linkDominio || "",
  localId: basicInfo.localId || "",
  localDescripcion: basicInfo.localDescripcion || "",
  localNombreComercial: basicInfo.localNombreComercial || "",
  localDireccion: basicInfo.localDireccion || "",
  localLatitud: basicInfo.localLatitud || "",
  localLongitud: basicInfo.localLongitud || "",
  localMontoMinimo: salesConfig.localMontoMinimo || "30.00",
  localIdioma: "es",
  localZonaHoraria: "America/Lima",
  localRedesSociales: basicInfo.localRedesSociales || "",
  localCartaGenerica: salesConfig.localCartaGenerica || "1",
  localDepartamento: basicInfo.localDepartamento || "",
  localProvincia: basicInfo.localProvincia || "",
  localDistrito: basicInfo.localDistrito || "",
  localTelefono: basicInfo.localTelefono || "",
  localWpp: basicInfo.localWpp || "",
  localPermiteComprobanteMenuOnline: salesConfig.localPermiteComprobanteMenuOnline || "1",
  monedaFacturacion: {
    monedaFacturacionId: "1",
    monedaFacturacionDescripcion: "Soles",
    monedaFacturacionSimbolo: "S/",
    monedaFacturacionIsocode: "PEN",
    monedaFacturacionChecksum: "abc123",
    monedaFacturacionEstado: "1",
    monedaList: [],
    precioLocalProductoList: [],
    precioLocalProductoMonedaList: []
  },
  localPorcentajeImpuesto: salesConfig.localPorcentajeImpuesto || "18",
  localLogo: basicInfo.localLogo || "",
  localImagenFondoMenuOnline: basicInfo.localImagenFondoMenuOnline || "",
  localFondoMenuOnlineSelector: "2",
  chatbotNumber: basicInfo.chatbotNumber || ""
});